version: '3.7'

x-defaults: &defaults
  image: ghcr.io/beamer-bridge/beamer-agent:0.1.3
  volumes:
    - ./data:/data
  logging:
    driver: json-file
    options:
      max-size: "1024m"
      max-file: "50"

services:
  agent1:
    << : *defaults
    restart: always
    # the agent command is included in the ENTRYPOINT declaration
    command: --config /data/agent-rinkeby.conf --source-chain boba --target-chain metis

  agent2:
    << : *defaults
    restart: always
    # the agent command is included in the ENTRYPOINT declaration
    command: --config /data/agent-rinkeby.conf --source-chain metis --target-chain boba
