version: '3.7'

x-defaults: &defaults
  image: ghcr.io/beamer-bridge/beamer-agent:v1.0.1
  volumes:
    - ./data:/data
  logging:
    driver: json-file
    options:
      max-size: "1024m"
      max-file: "50"

services:
  agent-optimism-to-arbitrum:
    << : *defaults
    restart: always
    # the agent command is included in the ENTRYPOINT declaration
    command: --config /data/agent-mainnet.conf --source-chain optimism --target-chain arbitrum

  agent-arbitrum-to-optimism:
    << : *defaults
    restart: always
    # the agent command is included in the ENTRYPOINT declaration
    command: --config /data/agent-mainnet.conf --source-chain arbitrum --target-chain optimism
