version: '3.7'

x-defaults: &defaults
  image: ghcr.io/beamer-bridge/beamer:v2.5.2
  volumes:
    - ./data:/data
  logging:
    driver: json-file
    options:
      max-size: "1024m"
      max-file: "50"

services:
  goerli-agent:
    << : *defaults
    restart: always
    # the agent command is included in the ENTRYPOINT declaration
    command: agent --config /data/agent-goerli.conf
