version: '3.7'

x-defaults: &defaults
  image: ghcr.io/beamer-bridge/beamer:v2.5.2
  volumes:
    - ./data:/data
  logging:
    driver: json-file
    options:
      max-size: "1024m"
      max-file: "50"

services:
  mainnet-agent:
    << : *defaults
    restart: always
    # the agent command is included in the ENTRYPOINT declaration
    command: agent --config /data/agent-mainnet.conf

  health-check:
    << : *defaults
    restart: always
    stdin_open: true
    entrypoint: /bin/sh
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.heartbeat.schedule: "@every 6h"
      ofelia.job-exec.heartbeat.no-overlap: "true"
      ofelia.job-exec.heartbeat.command: "beamer health-check --config /data/beamer-health-check.conf"

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - health-check
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:r
